---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:038462784735:task-definition/SpringBoot:1"
        LoadBalancerInfo:
          ContainerName: "sprinrajco"
          ContainerPort: 8080
