---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:038462784735:task-definition/SpringBootApplication:1"
        LoadBalancerInfo:
          ContainerName: "SpringBoot"
          ContainerPort: 8080
